// One-time scaffold script: creates data/manifest.json, the top-level index of
// test-management systems. Safe to re-run — only ever writes this one file.
const fs = require('fs');
const path = require('path');

const SYSTEMS = [
  {
    slug: 'modules', name: 'Module Test Management System', entityLabel: 'Module', dataDir: 'modules',
    description: 'Per-module test suites for the Vibrantix product and platform modules (Evidence Management, Risk Register, Audit Assurance, ...).',
  },
  {
    slug: 'frameworks', name: 'Frameworks Test Management System', entityLabel: 'Framework', dataDir: 'frameworks',
    description: 'Compliance framework requirements coverage and UCL (shared control layer) mapping correctness, per framework.',
  },
  {
    slug: 'logs', name: 'Logs Test Management System', entityLabel: 'Log Source', dataDir: 'logs',
    description: 'Correctness of logs generated by each module — audit trail, activity, and security event logging.',
  },
  {
    slug: 'audit-reports', name: 'Audits Report Test Management System', entityLabel: 'Framework Audit Report', dataDir: 'audit-reports',
    description: "Report field accuracy and completeness for each compliance framework's generated audit report.",
  },
  {
    slug: 'integrations', name: 'Integrations Management System', entityLabel: 'Connector', dataDir: 'integrations',
    description: 'Connector connection flows, authentication, and per-connector health/capability checks.',
  },
  {
    slug: 'defects', name: 'AI Defects Management System', entityLabel: 'Module', dataDir: 'defects', recordKind: 'defect',
    description: 'Real defects converted from the QA_Tracker/ live defect trackers — severity, status lifecycle, and full narrative per finding, read-only.',
  },
];

const root = path.join(__dirname, '..', 'data');
fs.writeFileSync(path.join(root, 'manifest.json'), JSON.stringify({ systems: SYSTEMS }, null, 2) + '\n');

console.log(`Wrote data/manifest.json with ${SYSTEMS.length} systems`);
